name: 部署到个人服务器

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - main

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # 1、生成静态文件
      - name: Build
        run: npm install && npm run build

      # Deploy
      - name: 部署到自己服务器
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.POSSIBLE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ vars.SERVER_ADDR }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          TARGET: ${{ vars.WWW }}

      # 2、部署到 GitHub Pages
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     REPOSITORY_NAME: padeyao4/possible
      #     BRANCH: page
      #     FOLDER: dist
          #注意这里的 public 是仓库根目录下的 public，也就是 npm run build 生成静态资源的路径，比如有的人是 `docs/.vuepress/dist`