name: 部署到个人服务器

# 触发条件：在 push 到 main 分支后
on:
  push:
    branches:
      - main

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4

      # 设置 Node.js 环境，使用版本 20，并启用 npm 缓存以加快依赖安装速度
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 生成静态文件
      - name: Build Project
        run: |
          npm install
          npm run web:build

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          # 服务器地址，从仓库变量中获取
          host: ${{ vars.SSH_HOST }}
          # 远程服务器用户名，从仓库变量中获取
          username: ${{ vars.SSH_USER }}
          # SSH私钥，从仓库秘密存储中获取，用于安全认证
          key: ${{ secrets.SSH_KEY }}
          # 要部署的源目录，即构建后的静态文件目录
          source: dist/
          # 目标服务器路径，从仓库变量中获取
          target: ${{ vars.SSH_WWW }}
          # 移除源路径中的一级目录
          strip_components: 1
          # 覆盖目标目录中的已存在文件
          overwrite: true
          # 删除目标目录中的多余文件
          rm: true
